#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.6
#  in conjunction with Tcl version 8.6
#    Nov 14, 2020 03:08:08 PM EST  platform: Windows NT

import sys
import interpolation.vandermonde as vandermonde
import interpolation.difDiv as difdiv
import interpolation.lagrange as lagrange
try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global combobox
    combobox = tk.StringVar()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None


def runMethod(choiceInteg,xEntry,yEntry, Scrolledtext1):
    Scrolledtext1.delete("1.0", 'end')
    k=choiceInteg.get()
    xstr = xEntry.get()
    ystr = yEntry.get()
    x = list(map(float, xstr.split(',')))
    y = list(map(float, ystr.split(',')))
    ops = ['Vandermonde', 'Divided differences', 'Lagrange' ]

    if k == ops[0]:  # vandermonde
        vandermonde.vanderMondeGUI(x, y,Scrolledtext1)
    elif k == ops[1]:  # dif div
        difdiv.interpolate_newtonGUI(x, y,Scrolledtext1)
    elif k == ops[2]:  # lagrange
        lagrange.lagrange_polGUI(x, y,Scrolledtext1)
    else:
        res='Please pick a method'



    return None

if __name__ == '__main__':
    import interpol
    interpol.vp_start_gui()




