#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.6
#  in conjunction with Tcl version 8.6
#    Nov 14, 2020 10:24:53 PM EST  platform: Windows NT
import linearSystems.iterativeMethods.jacobi as jacobi
import linearSystems.iterativeMethods.gaussSeidel as gseidel
import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global combobox
    combobox = tk.StringVar()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None
def string_to_matrix(str_in):
    nums = str_in.split(',')
    n = int(len(nums) ** 0.5)
    return list(map(list, zip(*[map(int, nums)] * n)))

def runMethod(choiceInteg, matrixEntry, vectorEntry,initalEntry, iterationsEntry, tolEntry, Scrolledtext1):
    Scrolledtext1.delete("1.0", 'end')
    k = choiceInteg.get()
    xstr = matrixEntry.get()
    ystr = vectorEntry.get()
    x0str = initalEntry.get()
    A = string_to_matrix(xstr)
    tol = float(tolEntry.get())
    maxit = int(iterationsEntry.get())
    b = list(map(float, ystr.split(',')))
    x0 = list(map(float, x0str.split(',')))
    ops = ['Jacobi','Gauss Seidel',]
    if k == ops[0]:
        jacobi.solveJacobi(A,b,x0,tol,maxit,Scrolledtext1)
    elif k == ops[1]:
        gseidel.solveGaussSeidel(A, b, x0, tol, maxit, Scrolledtext1)
    else:
        Scrolledtext1.insert(tk.INSERT, 'Please pick a method')

if __name__ == '__main__':
    import iterativeSys
    iterativeSys.vp_start_gui()




